### ISSUE TITLE
Local VAE 

### ISSUE THREAD

**Issue by hanish3464** [cientgu/Mask_Guided_Portrait_Editing#7]
Hi! Author!

I have a question about local embedding encoder!

1. Why did you use VAE in train code, not auto encoder (like paper) ?
There inserted decoder feature, not encoder feature in the 3D zero tensor... 

At the local phase, auto encoder seems to be more appropriate because feature compression is performed.

2. Can you tell me how the size criteria for the components of face are set? (32 x 48 , 80 x 144 ..)

Thank you for amazing contribution!

**Comment by cientgu** [comment]
> Hi! Author!
> 
> I have a question about local embedding encoder!
> 
> 1. Why did you use VAE in train code, not auto encoder (like paper) ?
>    There inserted decoder feature, not encoder feature in the 3D zero tensor...
> 
> At the local phase, auto encoder seems to be more appropriate because feature compression is performed.
> 
> 1. Can you tell me how the size criteria for the components of face are set? (32 x 48 , 80 x 144 ..)
> 
> Thank you for amazing contribution!

1.  Good question. The different of VAE and AE is a history problem: if we want to random sample from latent space?  Both VAE and AE works here, VAE will miss more information for reconstruction loss but can using sample to generate new images. The results of AE is much better than VAE. And in our code, we didn't use VAE-KL loss to update though we compute it.(sorry about the history problem...). The decoder feature and encoder feature are all OK since the reconstruction is almost perfect.
2. The size is shown in models/pic2pixHD_mask_model.py  line257-line281
